pipeline {
    agent any

    //       tools
    // {
    //    maven "Maven"
    // }
 stages {
    //   stage('checkout') {
    //        steps {

    //             git branch: 'master', url: 'https://github.com/vermasunilk792/java-maven-docker-cicd.git'

    //       }
    //     }
        //  stage('Execute Maven') {
        //    steps {

        //         sh 'mvn package'
        //   }
        // }
        //  stage('Docker user permission') {
        //    steps {

        //         sh 'docker run --rm -d --group-add $(stat -c '%g' /var/run/docker.sock) -v /var/run/docker.sock:/var/run/docker.sock -P samplewebapp:latest'

        //   }
        // }

         stage('Docker Build and Tag') {
           steps {

                sh 'docker build -t webapp:latest .'
                //sh 'docker run --rm -d --group-add $(stat -c '%g' /var/run/docker.sock) -v /var/run/docker.sock:/var/run/docker.sock -P samplewebapp:latest'
                sh 'docker tag webapp webapp:latest'
                
                // sh 'docker tag webapp java/webapp:$BUILD_NUMBER'

          }
        }



         stage('Publish image to Docker Hub') {
           steps {
                //   withDockerRegistry([ credentialsId: "dockerHub", url: "" ]) {
                  sh  'docker push webapp:latest'
                //  sh  'docker push sunilkv487/docker-jenkins:latest:$BUILD_NUMBER'
        //  }

           }
         }

         stage('Run Docker container on Jenkins Agent') {

            steps
                        {
                sh "docker run -d -p 8003:8080 webapp:latest"

            }
        }
         stage('Run Docker container on remote hosts') {

            steps {
		        sh "ssh-add"
                sh "docker -H ssh://ubuntu@54.172.226.69 run -d -p 8003:8080 webapp:latest"

            }
        }
    }
        }
